import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {
          `
          h2{
            font-size : 38px;
          }
          h3{
            font-size : 28px;
            margin-top : 1.5rem;
          }
          `
        }
      </style>
      <Head>
        <title>vvsdc's blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next.js,next , blogs ,blog , vvsdc'c blogs , vvsdc" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
        </ul>
      </nav>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1>VvSdC's blogs</h1>
          <div className={styles.imagewrap}>
            <Image className={styles.myImg} src='/home.avif' width={240} height={200} alt="Developers" />
          </div>
          <p className={styles.description}>A blog for developers by a developer.</p>
        </div>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn c++ in 2024 ?</h3>
            <p>C++ is a object oriented language</p>
          </div>
          <div className="blogItem">
            <h3>How to learn c++ in 2024 ?</h3>
            <p>C++ is a object oriented language</p>
          </div>
          <div className="blogItem">
            <h3>How to learn c++ in 2024 ?</h3>
            <p>C++ is a object oriented language</p>
          </div>
        </div>
      </main>
    </div>
  );
}
